kind: pipeline
name: mono-baseimage

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: ich777/mono-baseimage
    username: ich777
    password:
      from_secret: docker_password
    tags: latest